### PR TITLE
DOM tree creation and loop functions incorporated. #2

### PR DESCRIPTION
**Pull request by NoahLett**

### CODE REVIEW

**Comment by NoahLett** [comment]
[Untitled_ Nov 3, 2022 11_16 AM.webm](https://user-images.githubusercontent.com/110089434/199803175-7a01e0bb-3c48-4bf7-92bf-610b67be1a89.webm)

**Review by Zhiwutian — CHANGES_REQUESTED** [review]
Only update I see would be to use one `DOMContentLoaded` function to call looper and to call the view swapping function instead of two.

**Comment by NoahLett** [comment]
[Untitled_ Nov 3, 2022 12_50 PM.webm](https://user-images.githubusercontent.com/110089434/199820319-5417333c-6a67-4e4d-aef9-6f2fdc252833.webm)

**Review by Zhiwutian — APPROVED** [review]
👍🏼

**Pull request merged**
